apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
spec:
  selector:
    app: spring-boot-k8s
  ports:
  - protocol: "TCP"
    port: 9090 #Port that the service is running in the cluster
    targetPort: 9090 #Port that was exposed by the service
  type: NodePort #Type of the service

